civi_drest:
    resource: "@CiviDrestBundle/Controller/"
    type:     annotation
    prefix:   /civicrm

CiviFrameworkBundle:
    resource: "@CiviFrameworkBundle/Resources/config/routing.xml"
    prefix:   /civicrm

CiviFrameworkBundle:
    resource: .
    type:     civicrm_menu

CiviAdminBundle:
    resource: "@CiviAdminBundle/Controller/"
    type:     annotation
    prefix:   /civicrm/admin

CiviDrupalBundle:
    resource: "@CiviDrupalBundle/Resources/config/routing.xml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
